---
- block:
  - name: check rustup
    command: which cargo
    register: result
    check_mode: no
    changed_when: no
    failed_when: no

  - name: install rustup # shellを使わない書き方がうまくいかなかった
    shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path"
    args:
      warn: no
    when: result.rc == 1

  - import_tasks: ../common/tasks/copy_bashrc.yml

  tags:
    - rust
