---
- block:
  - name: check awscli
    command: which aws
    register: result
    check_mode: no
    changed_when: no
    failed_when: no

  - block:
    - name: download awscli installer
      get_url:
        url: https://awscli.amazonaws.com/AWSCLIV2.pkg
        dest: /tmp/AWSCLIV2.pkg
        validate_certs: no
      register: download

    - name: install awscli
      become: yes
      command: "installer -pkg {{ download.dest }} -target /"
 
    when: result.rc == 1

  - name: check session manager plugin
    command: session-manager-plugin
    register: result
    check_mode: no
    changed_when: no
    failed_when: no

  - block:
    - name: download session manager plugin
      unarchive:
        src: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip
        dest: /tmp
        remote_src: yes
        validate_certs: no
      register: smp

    - name: install session manager plugin
      become: yes
      command: "/usr/bin/python3 {{ smp.dest }}/sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin"

    when: result.rc != 0

  - import_tasks: ../common/tasks/copy_bashrc.yml

  tags:
    - awscli
