---
- block:
  - name: upgrade pip
    pip:
      executable: pip3
      name: pip
      extra_args: --user
      state: latest

  - name: install pip packages
    pip:
      executable: pip3
      name: "{{ item.name }}"
      extra_args: --user
      state: "{{ item.state }}"
    loop: "{{ packages }}"

  - import_tasks: ../common/tasks/copy_bashrc.yml

  tags:
    - pip
