# osx_defaultsがdictに対応していないためコマンドで実行する。
---
- block:
  # Option + tabで同一アプリ内のウインドウを切り替える
  - name: fetch hotkey 27
    shell: defaults read com.apple.symbolichotkeys AppleSymbolicHotKeys | grep '27 =' -A 10 | gsed -E -e 's/(\S*) =/"\1":/' | sed -e 's/standard;/"standard"/' | tr '()' '[]' | sed -e 's/};/}/' | sed -e 's/;/,/' | awk 'NR==1{sub(/^/, "{")} NR==11{sub(/$/, "}")} {print}'
    register: check_hotkey_27
    check_mode: no
    changed_when: no

  - name: change hotkey 27
    command: defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 27 '<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>48</integer><integer>524288</integer></array><key>type</key><string>standard</string></dict></dict>"'
    when: (check_hotkey_27.stdout | from_json) != ('{"27":{"enabled":1,"value":{"parameters":[65535,48,524288],"type":"standard"}}}' | from_json)

  # Ctrl + spaceのショートカットキーを無効化
  - name: check hotkey 60
    shell: "defaults read com.apple.symbolichotkeys AppleSymbolicHotKeys | grep ' 60 =' -1 | tail -1 | sed -e 's/ //g'"
    register: check_hotkey_60
    check_mode: no
    changed_when: no

  - name: disable hotkey 60
    command: defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 60 '<dict><key>enabled</key><false/></dict>'
    when: check_hotkey_60.stdout != 'enabled=0;'

  - name: check hotkey 61
    shell: "defaults read com.apple.symbolichotkeys AppleSymbolicHotKeys | grep ' 61 =' -1 | tail -1 | sed -e 's/ //g'"
    register: check_hotkey_61
    check_mode: no
    changed_when: no

  - name: disable hotkey 61
    command: defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 61 '<dict><key>enabled</key><false/></dict>'
    when: check_hotkey_61.stdout != 'enabled=0;'
