#!/bin/bash

export PATH="/usr/local/bin:$PATH"

#ignoredups+ignorespace
export HISTCONTROL=erasedups
export HISTIGNORE="history*:man*:fg*:bg*:ls*( -@(?|??)):pwd:jobs:export:env:exit"
export HISTSIZE=10000
export HISTTIMEFORMAT='%F %T '

PS1='\h:\W \u\$ '

for file in ~/.bashrc.d/*; do
  . "$file"
done