---
- block:
  - import_tasks: ../common/tasks/copy_bashrc.yml

  - name: fetch directory list
    local_action: "shell ls | grep -v bashrc"
    args:
      chdir: "{{ role_path }}/files"
    register: dirs
    check_mode: no
    changed_when: no
    failed_when: no

  - name: create config directory
    file:
      path: "~/.{{ item }}"
      state: directory
      mode: "0700"
    loop: "{{ dirs.stdout_lines }}"

  - name: copy config files
    copy:
      src: "{{ item }}/"
      dest: "~/.{{ item }}"
    loop: "{{ dirs.stdout_lines }}"

  - name: lookup ssh key files
    shell: "ls ~/.ssh/{id_rsa,*.pem}"
    check_mode: no
    changed_when: no
    register: path_files

  - name: change key files permission
    file:
      path: "{{ item }}"
      mode: "0600"
    loop: "{{ path_files.stdout_lines }}"

  - name: edit hosts
    include_tasks: hosts.yml
    with_first_found:
      - files:
        - hosts.yml
        skip: true

  tags:
    - _private
