---
- block:
  - import_tasks: ../common/tasks/copy_bashrc.yml

  - name: create config directory
    file:
      path: "~/.{{ item }}"
      state: directory
      mode: "0700"
    loop: "{{ targets }}"

  - name: copy config files
    copy:
      src: "{{ item }}/"
      dest: "~/.{{ item }}"
    loop: "{{ targets }}"

  - name: lookup ssh key files
    shell: "ls ~/.ssh/{id_rsa,*.pem}"
    check_mode: no
    changed_when: no
    register: path_files

  - name: change key files permission
    file:
      path: "{{ item }}"
      mode: "0600"
    loop: "{{ path_files.stdout_lines }}"

  tags:
    - _private
