---
- block:
  - name: install homebrew packages
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: "{{ packages }}"

  - import_tasks: ../common/tasks/copy_bashrc.yml

  tags:
    - homebrew
