---
- block:
  - name: install homebrew cask packages
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    homebrew_cask:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: "{{ packages }}"

  - name: check VSCode plugin
    shell: "code --list-extensions | grep {{ item }}"
    register: result
    check_mode: no
    changed_when: no
    failed_when: no
    loop: "{{ vscode_plugins }}"

  - name: install VSCode plugins
    shell: "code --install-extension {{ item.item }}"
    when: item.rc == 1
    loop: "{{ result.results }}"

  - name: copy vscode settings.json
    copy:
      src: vscode/settings.json
      dest: ~/Library/Application Support/Code/User/

  - name: copy Rancher Desktop override.yaml
    copy:
      src: rancher/override.yaml
      dest: ~/Library/Application Support/rancher-desktop/lima/_config/

  - import_tasks: ../common/tasks/copy_bashrc.yml

  tags:
    - homebrew_cask
